# .streamlit/secrets.toml
# Configuration file for Strive Pro Phase 2

# OpenRouter API Configuration
OPENROUTER_API_KEY = "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"

# Email Configuration (for advanced reporting)
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = "587"
SENDER_EMAIL = "your_email@gmail.com"
SENDER_PASSWORD = "your_app_password_here"  # Use app password for Gmail

# JWT Secret for Authentication (generate a secure random string)
jwt_secret = "your_super_secure_jwt_secret_key_here_minimum_32_characters"

# Database Configuration (optional - defaults to SQLite)
DATABASE_TYPE = "sqlite"  # sqlite, postgresql, mysql
DATABASE_URL = "sqlite:///strive_pro.db"

# Organization Settings
DEFAULT_ORG_NAME = "Default Organization"
DEFAULT_ORG_INDUSTRY = "Technology"

# ML Model Settings
ML_MODEL_PATH = "ml_models"
ENABLE_ML_PREDICTIONS = true
ML_CONFIDENCE_THRESHOLD = 0.7

# Advanced Features
ENABLE_EMAIL_NOTIFICATIONS = true
ENABLE_CALENDAR_INTEGRATION = true
ENABLE_PDF_REPORTS = true
ENABLE_ORGANIZATION_ANALYTICS = true

# Development Settings
DEBUG_MODE = false
LOG_LEVEL = "INFO"

# Deployment Settings
DEPLOYED_URL = "https://your-app-domain.com"  # Used for calendar links and email callbacks