# Copy this file to secrets.toml and fill in your values

[email]
sender_email = "your-email@gmail.com"
sender_password = "your-app-password"

[security]
jwt_secret_key = "your-super-secret-key-change-this"
